### ISSUE TITLE
BlockIgniteEvent - This is when I jailed myself as a test.

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#19]
2012-11-12 11:14:44 [SEVERE] Could not pass event BlockIgniteEvent to CommandsEX v1.98
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.BlockFire.b(BlockFire.java:150)
    at net.minecraft.server.WorldServer.a(WorldServer.java:477)
    at net.minecraft.server.WorldServer.doTick(WorldServer.java:169)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:565)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:495)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NullPointerException
    at com.github.zathrus_writer.commandsex.helpers.Common.checkFrozenState(Common.java:611)
    at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 11 more

**Comment by keir-nellyer** [comment]
Ah turns out we already fixed that one :D Will be included in Release 2.0
