### ISSUE TITLE
XMPP bridge throws ClassCastException

### ISSUE THREAD

**Issue by jinks** [CommandsEX/Minecraft-CommandsEX#22]
Hi,
I tried setting up the XMPP for my private server. While the bot connects to the room without problem, no relaying of messages or commands is done.
The jabber server I'm trying to reach is powered by [Prosody](http://www.prosody.im/).

The following StackTrace is in the server logs:

```
15:01:49 [INFO] [CommandsEX] Connecting to XMPP (Jabber) room...
15:01:50 [SEVERE] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
15:01:50 [SEVERE] java.lang.ClassCastException: org.jivesoftware.smack.util.PacketParserUtils$2 cannot be cast to org.jivesoftware.smackx.packet.
MUCAdmin
15:01:50 [SEVERE]       at org.jivesoftware.smackx.muc.MultiUserChat.getOccupants(MultiUserChat.java:1797)
15:01:50 [SEVERE]       at org.jivesoftware.smackx.muc.MultiUserChat.getParticipants(MultiUserChat.java:1772)
15:01:50 [SEVERE]       at com.github.zathrus_writer.commandsex.helpers.XMPPer.<init>(XMPPer.java:70)
15:01:50 [SEVERE]       at com.github.zathrus_writer.commandsex.handlers.Handler_xmpp.<init>(Handler_xmpp.java:30)
15:01:50 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15:01:50 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
15:01:50 [SEVERE]       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
15:01:50 [SEVERE]       at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
15:01:50 [SEVERE]       at java.lang.Class.newInstance0(Class.java:372)
15:01:50 [SEVERE]       at java.lang.Class.newInstance(Class.java:325)
15:01:50 [SEVERE]       at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:155)
15:01:50 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
15:01:50 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
15:01:50 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
15:01:50 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:300)
15:01:50 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:282)
15:01:50 [SEVERE]       at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
15:01:50 [SEVERE]       at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
15:01:50 [SEVERE]       at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
15:01:50 [SEVERE]       at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:147)
15:01:50 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:398)
15:01:50 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
```

Which only leads me to http://community.igniterealtime.org/thread/47377, suggesting a ClassPath problem. I'm not familiar with smack, so I don't know if that is at all related to the way CommandsEX uses it.

**Comment by keir-nellyer** [comment]
Will take a look at that soon, thanks for reporting!

**Comment by keir-nellyer** [comment]
@jinks I think I may have fixed it, will try to release version 2.0 soon! Your detailed bug report really helped, I was about to give up and saw the link. To answer your question, CommandsEX does use smack and smackx.

**Comment by JamesNorris** [comment]
This problem has not yet been fixed. Expect an update soon that will fix this. Thanks!

**Comment by keir-nellyer** [comment]
Yeah sorry, thought I had fixed that but turns out not, will look into fixing this!

**Comment by keir-nellyer** [comment]
I think I fixed this, will try to get a build out today
