### ISSUE TITLE
Odd Issue

### ISSUE THREAD

**Issue by ethan476** [CommandsEX/Minecraft-CommandsEX#32]
[SEVERE] Could not load 'plugins/CommandsEX.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/zathrus_writer/commandsex/CommandsEX : Unsupported major.minor version 51.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:235)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:213)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.UnsupportedClassVersionError: com/github/zathrus_writer/commandsex/CommandsEX : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
        ... 9 more

any ideas?

**Comment by keir-nellyer** [comment]
That is very weird. Did you use the Builder to create the JAR? If so which one (Stable or Dev) or did you download it from BukkitDev or SourceForge

**Comment by ethan476** [comment]
I tried builder and craft bukkit, I'm using linux CentOS

**Comment by keir-nellyer** [comment]
Can you send me your CommandsEX jar file please?

**Comment by JamesNorris** [comment]
This looks like a problem with outdated versions...

**Comment by keir-nellyer** [comment]
@JamesNorris I don't think it is, looks like the version in plugin.yml is 51.0. That's why I'd like to see his jar file.

**Comment by JamesNorris** [comment]
@iKeirNez May be, but then why would he change it inside the jar to version 51.0? And why wouldn't it load that? It should load any version you change it to.

**Comment by keir-nellyer** [comment]
@JamesNorris I have no idea, we can't tell without the jar.
