### ISSUE TITLE
CommandsEX support for Bukkitforge/Feed the beast?

### ISSUE THREAD

**Issue by l1nuxfre4k** [CommandsEX/Minecraft-CommandsEX#33]
Im using Feed the beast/Mindcrack and Bukkitforge(https://github.com/keepcalm/BukkitForge) i need CommandsEX for my server :)
I tried using it and i keep getting error, dont know if it might be an easy fix, can you help?

2013-01-15 20:23:48 [INFO] [com.github.zathrus_writer.commandsex.CommandsEX] [CommandsEX] Enabling CommandsEX v2.0
2013-01-15 20:23:48 [INFO] [Minecraft] [CommandsEX] Starting with locale (translation): en
2013-01-15 20:23:48 [INFO] [Minecraft] [CommandsEX] version 2.0 has successfully started.
2013-01-15 20:23:48 [SEVERE] [Minecraft] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
2013-01-15 20:23:48 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.handlers.Handler_condensejoins.<clinit>(Handler_condensejoins.java:35)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.forName0(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.forName(Class.java:186)
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2013-01-15 20:23:48 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-15 20:23:48 [INFO] [STDERR]     ... 12 more
2013-01-15 20:23:48 [SEVERE] [Minecraft] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
2013-01-15 20:23:48 [INFO] [STDERR] java.lang.NoClassDefFoundError: org/jivesoftware/smack/PacketListener
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName0(JavaPluginLoader.java:302)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:76)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.handlers.Handler_xmpp.<init>(Handler_xmpp.java:30)
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.newInstance0(Class.java:372)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.newInstance(Class.java:325)
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2013-01-15 20:23:48 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.PacketListener
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-15 20:23:48 [INFO] [STDERR]     ... 31 more
2013-01-15 20:23:48 [SEVERE] [Minecraft] Either Vault plugin was not found or there is no permissions plugin present. Therefore, timed automatic promotions will not work.
2013-01-15 20:23:48 [SEVERE] [Minecraft] Either Vault plugin was not found or there is no permissions or economy plugin present. Therefore, automatic promotions based on wealth will not work.
2013-01-15 20:23:48 [WARNING] [Minecraft] [CommandsEX] Could not activate group changing after player's death because Vault plugin is not installed. Vault is required for all group management functions in CommandsEX.
2013-01-15 20:23:48 [SEVERE] [Minecraft] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
2013-01-15 20:23:48 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/Packet
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.forName0(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Class.forName(Class.java:186)
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2013-01-15 20:23:48 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.Packet
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-15 20:23:48 [INFO] [STDERR]     ... 11 more
2013-01-15 20:23:48 [SEVERE] [Minecraft] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
2013-01-15 20:23:48 [INFO] [STDERR] java.lang.reflect.InvocationTargetException
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-15 20:23:48 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:179)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
2013-01-15 20:23:48 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2013-01-15 20:23:48 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
2013-01-15 20:23:48 [INFO] [STDERR]     at com.github.zathrus_writer.commandsex.helpers.Quizzes.init(Quizzes.java:63)
2013-01-15 20:23:48 [INFO] [STDERR]     ... 13 more
2013-01-15 20:23:48 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2013-01-15 20:23:48 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-15 20:23:48 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-15 20:23:48 [INFO] [STDERR]     ... 14 more

**Comment by keir-nellyer** [comment]
You need the latest version of CommandsEX for 1.4.6 found at the top of the BukkitDev description http://dev.bukkit.org/server-mods/commandsex/
Please note: Jenkins is currently broken and I am looking into it, for now you will only be able to use the Dev Builder.
