### ISSUE TITLE
Error when using /inv and /amessage

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#34]
I am using the CommandsEX dev build for 1.4.7 on my Tekkit Server with MCPC+ which integrates the CB 1.4.7 R1.1 (tested with 1.4.7 R0.1 too)  in Forge and i am getting this error in chat when using /invisible (or aliases):

"An internal error occured. Please..."

My console says: "[CommandsEX] Couldn´t handle function call 'cex_inv' "

The same thing happens for the /amessage command.

"[CommandsEX] Couldn´t handle function call 'cex_amessage' "

P.S. if it matters: I used the Builder for those two commands and /enderchest, /invsee, /freeze

**Comment by keir-nellyer** [comment]
Can you please enable debugMode in the config and paste the errors here?

**Comment by ghost** [comment]
I was able to view the /inv error but i have no other player online atm so i was not able to log the /amsg command.
log:
2013-02-09 15:59:56 [INFO] [Cakestory] /inv 
2013-02-09 15:59:56 [SEVERE] [CommandsEX] Couldn't handle function call 'cex_inv'
2013-02-09 15:59:56 [INFO] Message: null, cause: java.lang.NoClassDefFoundError: com/github/zathrus_writer/commandsex/handlers/Handler_condensejoins
2013-02-09 15:59:56 [SEVERE] java.lang.reflect.InvocationTargetException
2013-02-09 15:59:56 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-09 15:59:56 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-09 15:59:56 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-09 15:59:56 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-09 15:59:56 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Commands.onCommand(Commands.java:68)
2013-02-09 15:59:56 [SEVERE]    at com.github.zathrus_writer.commandsex.CommandsEX.onCommand(CommandsEX.java:385)
2013-02-09 15:59:56 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-02-09 15:59:56 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2013-02-09 15:59:56 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:543)
2013-02-09 15:59:56 [SEVERE]    at iv.d(NetServerHandler.java:1390)
2013-02-09 15:59:56 [SEVERE]    at iv.chat(NetServerHandler.java:1258)
2013-02-09 15:59:56 [SEVERE]    at iv.a(NetServerHandler.java:1182)
2013-02-09 15:59:56 [SEVERE]    at cu.a(Packet3Chat.java:59)
2013-02-09 15:59:56 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-02-09 15:59:56 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-02-09 15:59:56 [SEVERE]    at iw.b(NetworkListenThread.java:57)
2013-02-09 15:59:56 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-02-09 15:59:56 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:979)
2013-02-09 15:59:56 [SEVERE]    at ho.r(DedicatedServer.java:301)
2013-02-09 15:59:56 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:855)
2013-02-09 15:59:56 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:742)
2013-02-09 15:59:56 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-02-09 15:59:56 [SEVERE] Caused by: java.lang.NoClassDefFoundError: com/github/zathrus_writer/commandsex/handlers/Handler_condensejoins
2013-02-09 15:59:56 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Common.inv(Common.java:505)
2013-02-09 15:59:56 [SEVERE]    at com.github.zathrus_writer.commandsex.commands.Command_cex_inv.run(Command_cex_inv.java:21)
2013-02-09 15:59:56 [SEVERE]    ... 22 more

**Comment by keir-nellyer** [comment]
Ok, I've fixed this issue in a commit but haven't pushed it yet. I'll push once I have fixed the rest of the errors

**Comment by ghost** [comment]
Ok, thx.

**Comment by keir-nellyer** [comment]
Be sure to let us know of any more issues you come across
