### ISSUE TITLE
Error when using /amessage

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#35]
Hi, i was now able to log the /amessage error in console if you haven´t already fixed it.
Log:

2013-02-10 14:00:17 [INFO] project_peace issued server command: /amsg Cakestory Wubbaa
2013-02-10 14:00:17 [SEVERE] [CommandsEX] Couldn't handle function call 'cex_amessage'
2013-02-10 14:00:17 [INFO] Message: null, cause: java.lang.NullPointerException
2013-02-10 14:00:17 [SEVERE] java.lang.reflect.InvocationTargetException
2013-02-10 14:00:17 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-10 14:00:17 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-10 14:00:17 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-10 14:00:17 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-10 14:00:17 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Commands.onCommand(Commands.java:68)
2013-02-10 14:00:17 [SEVERE]    at com.github.zathrus_writer.commandsex.CommandsEX.onCommand(CommandsEX.java:385)
2013-02-10 14:00:17 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-02-10 14:00:17 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2013-02-10 14:00:17 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:543)
2013-02-10 14:00:17 [SEVERE]    at iv.d(NetServerHandler.java:1390)
2013-02-10 14:00:17 [SEVERE]    at iv.chat(NetServerHandler.java:1258)
2013-02-10 14:00:17 [SEVERE]    at iv.a(NetServerHandler.java:1182)
2013-02-10 14:00:17 [SEVERE]    at cu.a(Packet3Chat.java:59)
2013-02-10 14:00:17 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-02-10 14:00:17 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-02-10 14:00:17 [SEVERE]    at iw.b(NetworkListenThread.java:57)
2013-02-10 14:00:17 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-02-10 14:00:17 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:979)
2013-02-10 14:00:17 [SEVERE]    at ho.r(DedicatedServer.java:301)
2013-02-10 14:00:17 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:855)
2013-02-10 14:00:17 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:742)
2013-02-10 14:00:17 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-02-10 14:00:17 [SEVERE] Caused by: java.lang.NullPointerException
2013-02-10 14:00:17 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Utils.replaceChatColors(Utils.java:276)
2013-02-10 14:00:17 [SEVERE]    at com.github.zathrus_writer.commandsex.commands.Command_cex_amessage.run(Command_cex_amessage.java:44)
2013-02-10 14:00:17 [SEVERE]    ... 22 more

**Comment by keir-nellyer** [comment]
Please add the line
aMessagePrefix: '&c[ADMIN] ' 
to the bottom of your config. This is caused by the Builder not copying that into the config.
