### ISSUE TITLE
Joinfull

### ISSUE THREAD

**Issue by Weirdje** [CommandsEX/Minecraft-CommandsEX#40]
I don't know why, but the cex.joinfull perm doesn't seem to work.
It does work when you're an op, but i also want to give it to vips and staff members.

(Also a quick non-bug question: Will the wiki be updated soon?)

**Comment by keir-nellyer** [comment]
It should work, if it works as op then it should work with a permission plugin. Which permissions plugin are you using?

**Comment by Weirdje** [comment]
I currently use PermissionsBukkit

**Comment by keir-nellyer** [comment]
I have no idea why it isn't working as PermissionsBukkit registers permissions when a player logs in and CommandsEX then see's if they have permission after PermBukkit has registered the player.

Could you possible upload or email me your permission settings to keir@nellyer.co.uk

Thanks!

**Comment by Weirdje** [comment]
Sure, will send an email right away :)

**Comment by keir-nellyer** [comment]
Thanks, I have no idea why its doing that. I'll try adding a Vault permission check too encase permissions aren't initializing when the player is logging in.

**Comment by keir-nellyer** [comment]
I'll keep this open until this is confirmed fixed when the next update is released.

**Comment by Weirdje** [comment]
Please inform me when the update is out and I'll try to report as soon as I know if it works (or not) :)

**Comment by keir-nellyer** [comment]
Actually if you email me your jar file I can add it.

**Comment by Weirdje** [comment]
Got an error while starting the server

2013-02-15 16:12:52 [INFO] [CommandsEX] Enabling CommandsEX v2.1 DEV
2013-02-15 16:12:52 [INFO] [CommandsEX] Starting with locale (translation): en
2013-02-15 16:12:52 [INFO] [CommandsEX] version 2.1 DEV has successfully started.
2013-02-15 16:12:52 [SEVERE] An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
2013-02-15 16:12:52 [SEVERE] java.lang.Error: Unresolved compilation problems: 
    The import com.avaje cannot be resolved
    The import org.bukkit.entity.Player cannot be resolved
    The import org.bukkit.event.EventHandler cannot be resolved
    The import org.bukkit.event.Listener cannot be resolved
    The import org.bukkit.event.player.PlayerLoginEvent cannot be resolved
    The import org.bukkit.event.player.PlayerLoginEvent cannot be resolved
    Listener cannot be resolved to a type
    The method getServer() is undefined for the type CommandsEX
    EventHandler cannot be resolved to a type
    PlayerLoginEvent cannot be resolved to a type
    Result cannot be resolved to a variable
    Player cannot be resolved to a type

2013-02-15 16:12:52 [SEVERE]    at com.github.zathrus_writer.commandsex.handlers.Handler_joinfull.<init>(Handler_joinfull.java:3)
2013-02-15 16:12:52 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2013-02-15 16:12:52 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2013-02-15 16:12:52 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2013-02-15 16:12:52 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2013-02-15 16:12:52 [SEVERE]    at java.lang.Class.newInstance0(Class.java:372)
2013-02-15 16:12:52 [SEVERE]    at java.lang.Class.newInstance(Class.java:325)
2013-02-15 16:12:52 [SEVERE]    at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:163)
2013-02-15 16:12:52 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-02-15 16:12:52 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
2013-02-15 16:12:52 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-02-15 16:12:52 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:282)
2013-02-15 16:12:52 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:264)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.j(MinecraftServer.java:321)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.e(MinecraftServer.java:300)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.a(MinecraftServer.java:259)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.DedicatedServer.init(DedicatedServer.java:149)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:399)
2013-02-15 16:12:52 [SEVERE]    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
