### ISSUE TITLE
/inv doen´t show joinmessage and if turned off still shows leavemessage

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#41]
Hi,
the /inv command has to bugs:
1. Fakejoin doesn´t give a message. Instead an error is shown in chat (not console)
2. When i turn off the fakemessages (or at least fakeleave) in config it still shows the leavemessage ingame.

There are no console errors (in debug mode).

Also, could you please make the message configurable? My normal ones are in german so a player would see that i vanished.

**Comment by keir-nellyer** [comment]
1) Please enable debugMode and send us the error
2) Fake join and Fake leave messages are for when I player toggles invisibility on or off.

**Comment by ghost** [comment]
1) Sorry i thought debug mode was already enabled.
Here is the log:

2013-02-15 22:54:32 [INFO] Cakestory issued server command: /inv
2013-02-15 22:54:32 [SEVERE] [CommandsEX] Couldn't handle function call 'cex_inv'
2013-02-15 22:54:32 [INFO] Message: null, cause: java.lang.NoClassDefFoundError: com/github/zathrus_writer/commandsex/handlers/Handler_condensejoins
2013-02-15 22:54:32 [SEVERE] java.lang.reflect.InvocationTargetException
2013-02-15 22:54:32 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-15 22:54:32 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-15 22:54:32 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-15 22:54:32 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-15 22:54:32 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Commands.onCommand(Commands.java:68)
2013-02-15 22:54:32 [SEVERE]    at com.github.zathrus_writer.commandsex.CommandsEX.onCommand(CommandsEX.java:385)
2013-02-15 22:54:32 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-02-15 22:54:32 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2013-02-15 22:54:32 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:543)
2013-02-15 22:54:32 [SEVERE]    at iv.d(NetServerHandler.java:1390)
2013-02-15 22:54:32 [SEVERE]    at iv.chat(NetServerHandler.java:1258)
2013-02-15 22:54:32 [SEVERE]    at iv.a(NetServerHandler.java:1182)
2013-02-15 22:54:32 [SEVERE]    at cu.a(Packet3Chat.java:59)
2013-02-15 22:54:32 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-02-15 22:54:32 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-02-15 22:54:32 [SEVERE]    at iw.b(NetworkListenThread.java:57)
2013-02-15 22:54:32 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-02-15 22:54:32 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:979)
2013-02-15 22:54:32 [SEVERE]    at ho.r(DedicatedServer.java:301)
2013-02-15 22:54:32 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:855)
2013-02-15 22:54:32 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:742)
2013-02-15 22:54:32 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-02-15 22:54:32 [SEVERE] Caused by: java.lang.NoClassDefFoundError: com/github/zathrus_writer/commandsex/handlers/Handler_condensejoins
2013-02-15 22:54:32 [SEVERE]    at com.github.zathrus_writer.commandsex.helpers.Common.inv(Common.java:490)
2013-02-15 22:54:32 [SEVERE]    at com.github.zathrus_writer.commandsex.commands.Command_cex_inv.run(Command_cex_inv.java:21)
2013-02-15 22:54:32 [SEVERE]    ... 22 more

2) You may have missunderstood what i wrote.
   In the cex config.yml are two options:

   fakeQuitMessage: false
   fakeJoinMessage: false

Both are set to false but it still shows the FakeQuitMessage. <Player> left the game.
I bet it would show the FakeJoinMessage too if there weren´t this error occuring.
My intention was that i tought this option should disable those messages but it doesn´t.

3) It would be very nice if you could support setting the messages in the config file.
    "<player> left the game." is obstrucive when your normal quitmessage is set to:
    "<player> ist nicht mehr online." (german version on my server).
    If i am not able to change the those messages, my players would see that i didn´t left the game for real.
    Without translation the fakemessages are not usable for servers with other "standard" messages.

```
If this feature is already included, please tell me where to find it?
```
