### ISSUE TITLE
it keeps saying this pls help and can you teach me how to create my very own custom plugins

### ISSUE THREAD

**Issue by grim2** [CommandsEX/Minecraft-CommandsEX#61]
An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R2/World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.handlers.Handler_condensejoins.<clinit>(Handler_condensejoins.java:35)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.Class.forName0(Native Method)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.Class.forName(Class.java:264)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:166)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R2.World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        ... 15 more
[21:49:27 ERROR]: An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R2/World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.helpers.XMPPer.<clinit>(XMPPer.java:43)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.handlers.Handler_xmpp.<init>(Handler_xmpp.java:30)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.Class.newInstance(Class.java:442)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:166)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R2.World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        ... 19 more
[21:49:27 ERROR]: Either Vault plugin was not found or there is no permissions or economy plugin present. Therefore, automatic promotions based on wealth will not work.
[21:49:27 ERROR]: An internal error has occured. Please try again, download a newer version of CommandsEX or contact the author.

[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.reflect.Method.invoke(Method.java:497)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:182)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R2/World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at com.github.zathrus_writer.commandsex.helpers.Quizzes.init(Quizzes.java:63)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        ... 16 more
[21:49:27 WARN](java.lang.reflect.InvocationTargetException): Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R2.World
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:49:27 WARN](java.lang.reflect.InvocationTargetException):        ... 17 more
[21:49:28 INFO](http://dev.bukkit.org/server-mods/commandsex): A new version of CommandsEX is available!

**Comment by keir-nellyer** [comment]
CommandsEX hasn't been updated in at least 2 years now, it's abandoned as I simply don't have the time for it anymore due to school, work and other things going on. You should find an alternative plugin, such as Essentials.

As for learning how to make your own plugins, a good place to start would be to learn how to make simple Java console applications. Once you feel you have a good enough grasp on that, you can start learning to make Bukkit plugins. There are many tutorials and videos out there as well as the Bukkit community which can help you along the way.

Hope I managed to help you, at least a little bit. Have fun learning to program, you won't regret it. :)
