### ISSUE TITLE
Issues..

### ISSUE THREAD

**Issue by Xarias09** [CommandsEX/Minecraft-CommandsEX#9]
1. Make broadcast works at console ;s
2. Error at newest Craftbukkit + CommandsEx
   http://pastebin.com/PuaiaJK4

Srry for short ticket but i dont have time :D

**Comment by Xarias09** [comment]
Next error:

2012-10-20 18:28:28 [SEVERE] Could not pass event BlockIgniteEvent to CommandsEX v1.98
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
    at net.minecraft.server.BlockStationary.b(BlockStationary.java:63)
    at net.minecraft.server.WorldServer.g(WorldServer.java:370)
    at net.minecraft.server.WorldServer.doTick(WorldServer.java:171)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:541)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.github.zathrus_writer.commandsex.helpers.Common.checkFrozenState(Common.java:611)
    at sun.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:474)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 12 more

Spam my loooogssss D:

**Comment by keir-nellyer** [comment]
Thanks for reporting this! Fixed all 3 of these issues/suggestions. This is much appreciated and if you have any more feature/suggestions then feel free to open another issue! We will gladly add them!

This fix will be available in Release 2.0 which I hope to push out very soon!

**Comment by Xarias09** [comment]
Command "/r" missing spaces between words.

When i type example: 

hiii IKERINEZ plugin appearing this message: hiiiIKERINEZ

**Comment by keir-nellyer** [comment]
Yeah, sorrry about that! We already fixed this and it will be in Release 2.0

**Comment by Xarias09** [comment]
And correct please plugin.yml at builder :p

**Comment by Xarias09** [comment]
Next error:
"at com.github.zathrus_writer.commandsex.helpers.Common$Unslap.run(Common.java:92)"

Random Spawn v2.3 plugin:

2012-10-21 18:48:17 [SEVERE] Could not pass event PlayerTeleportEvent to Random Spawn v2.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:356)
    at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:162)
    at com.github.zathrus_writer.commandsex.helpers.Common$Unslap.run(Common.java:92)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at me.Josvth.RandomSpawn.RandomSpawn.sendGround(RandomSpawn.java:221)
    at me.Josvth.RandomSpawn.Listeners.JoinListener.onPlayerTeleport(JoinListener.java:30)
    at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:474)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 13 more

Same error with NoCheatPlus:
"at com.github.zathrus_writer.commandsex.helpers.Common$Unslap.run(Common.java:92)"

NoCheatPlus v3.7.5-b164 (DEV):
2012-10-21 18:48:17 [SEVERE] Could not pass event PlayerTeleportEvent to NoCheatPlus v3.7.5-b164
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:356)
    at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:162)
    at com.github.zathrus_writer.commandsex.helpers.Common$Unslap.run(Common.java:92)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at fr.neatmonster.nocheatplus.checks.moving.MovingData.resetPositions(MovingData.java:181)
    at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerTeleport(MovingListener.java:556)
    at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:474)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 13 more

**Comment by keir-nellyer** [comment]
What do you mean by correct plugin.yml at Builder and I will look into that error, not quite sure why its happening.

**Comment by Xarias09** [comment]
Because when i generate my own compilate i have this errors:

2012-10-20 10:46:53 [SEVERE] Could not load 'plugins\CommandsEX.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:207)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:132)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:227)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:203)
    at net.minecraft.server.ServerConfigurationManagerAbstract.<init>(ServerConfigurationManagerAbstract.java:50)
    at net.minecraft.server.ServerConfigurationManager.<init>(SourceFile:11)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: while parsing a block mapping
 in "<reader>", line 1, column 1:
    authors: [Zathrus Writer, Keir N ... 
    ^
expected <block end>, but found BlockMappingStart
 in "<reader>", line 1047, column 3:
      cex_amessage:
      ^

```
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:42)
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:202)
... 8 more
```

**Comment by keir-nellyer** [comment]
Thought I already fixed that, try again, I re-uploaded the fix
